version: "3.9"

services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    restart: unless-stopped
    ports:
      - "5005:5432"
    volumes:
      - db:/data/postgres

volumes:
  db:
