// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPlaylistAssociationSnapshot struct {
	ChildPlaylistID  string `json:"childPlaylistId"`
	ParentPlaylistID string `json:"parentPlaylistId"`
}

type NewPlaylistSnapshot struct {
	Name              string                            `json:"name"`
	PlaylistID        string                            `json:"playlistId"`
	SpotifyPlaylistID *string                           `json:"spotifyPlaylistId"`
	PlaylistOrder     []*int                            `json:"playlistOrder"`
	Associations      []*NewPlaylistAssociationSnapshot `json:"associations"`
}

type NewPlaylistSnapshotConfiguration struct {
	Playlists []*NewPlaylistSnapshot `json:"playlists"`
}

type NewSyncPlaylistsEvent struct {
	SnapshotID string `json:"snapshotId"`
}

type PlaylistAssociationSnapshot struct {
	ID               string `json:"id"`
	ChildPlaylistID  string `json:"childPlaylistId"`
	ParentPlaylistID string `json:"parentPlaylistId"`
}

type PlaylistSnapshot struct {
	ID                string                         `json:"id"`
	Name              string                         `json:"name"`
	SpotifyPlaylistID *string                        `json:"spotifyPlaylistId"`
	PlaylistOrder     []*int                         `json:"playlistOrder"`
	Associations      []*PlaylistAssociationSnapshot `json:"associations"`
}

type PlaylistSnapshotConfiguration struct {
	ID        string              `json:"id"`
	Playlists []*PlaylistSnapshot `json:"playlists"`
}

type SyncPlaylistsEvent struct {
	ID                    string                         `json:"id"`
	UserID                string                         `json:"userId"`
	ConfigurationSnapshot *PlaylistSnapshotConfiguration `json:"configurationSnapshot"`
}
