syntax = "proto3";
package mixify;

service Mixify {
    rpc AuthState(Empty) returns (AuthStateResponse) {}
    rpc CreateTokenUrl(Empty) returns (CreateTokenUrlResponse) {}
    rpc SubmitTokenCode(SubmitTokenRequestCode) returns (User) {}

    rpc Plan(SnapshotRequest) returns (stream OutputResponse) {}
    rpc Apply(SnapshotRequest) returns (OutputResponse) {}
    rpc Sync(SnapshotRequest) returns (OutputResponse) {}
}

enum LoginStatus {
    LOGGED_IN = 0;
    NOT_LOGGED_IN = 1;
}

message Empty {}

message User {
    optional string display_name = 1;
    string id = 2;
}

message AuthStateResponse {
    LoginStatus status = 1;
    optional User user = 2;
}

message CreateTokenUrlResponse { string url = 1; }

message SubmitTokenRequestCode { string url = 1; }

message SnapshotRequest { string snapshot_content = 1; }

message OutputResponse { string output = 1; }

